from celery import shared_task
from app.db.session import AsyncSessionLocal
from app.models.job import JobStatus
from app.models.project import Project
from app.models.deliverables import Deliverable
from app.services.packager import package_deliverable
from app.services.notification import notification_service
import asyncio
import os

@shared_task(bind=True, max_retries=2)
def run_packager_task(self, project_id, client_email, job_id):
    async def _run():
        async with AsyncSessionLocal() as db:
            try:
                job = await db.get(Job, job_id)
                project = await db.get(Project, project_id)
                if not job or not project: return {"error": "Not found"}
                job.status = JobStatus.RUNNING
                await db.commit()
                output_dir = f"/app/deliverables/project_{project_id}"
                code_dir = os.path.join(output_dir, "code")
                landing_dir = os.path.join(output_dir, "landing")
                promo_dir = os.path.join(output_dir, "promo")
                invoice_pdf = os.path.join(output_dir, "invoice.pdf")
                readme = f"# {project.name}\\n\\nGenerated by AI Product Studio v4.0\\n\\n## Contents\\n- code/ - Source\\n- landing/ - Landing page\\n- promo/ - Marketing\\n- invoice.pdf - Receipt\\n\\n## Support\\nsupport@aiproductstudio.com"
                deploy = "# Deployment\\n1. Extract ZIP\\n2. cd code/\\n3. docker compose up -d\\n\\n## Requirements\\n- Docker 24.0+\\n- 16GB RAM"
                zip_path = package_deliverable(project_id=project_id, project_name=project.name, code_dir=code_dir, landing_dir=landing_dir, promo_dir=promo_dir, invoice_pdf=invoice_pdf, readme_content=readme, deploy_content=deploy)
                deliverable = Deliverable(project_id=project_id, zip_path=zip_path, contents=["code", "landing", "promo", "invoice", "readme", "deploy"], client_email=client_email)
                db.add(deliverable)
                job.status = JobStatus.COMPLETED
                job.result = {"deliverable_id": deliverable.id, "zip": zip_path}
                await db.commit()
                await notification_service.create_project_complete_notification(project.name)
                return {"status": "completed", "zip": zip_path}
            except Exception as e:
                job.status = JobStatus.FAILED
                job.error = str(e)
                await db.commit()
                self.retry(countdown=60, exc=e)
                return {"error": str(e)}
    return asyncio.run(_run())
