from celery import shared_task
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import sessionmaker
from app.db.session import engine
from app.models.job import Job, JobStatus
from app.models.project import Project, ProjectStatus
from app.models.invoice import Invoice
from app.services.stripe_service import create_payment_link, generate_invoice_pdf
from app.services.packager import package_deliverable
import os


@shared_task(bind=True, max_retries=2)
def run_sales_task(self, project_id: int, job_id: int):
    import asyncio

    async def _run():
        async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
        async with async_session() as db:
            try:
                job = await db.get(Job, job_id)
                project = await db.get(Project, project_id)

                if not job or not project:
                    return {"error": "Job or project not found"}

                job.status = JobStatus.RUNNING
                await db.commit()

                output_dir = f"/app/deliverables/project_{project_id}"

                # Create payment link ($100 default)
                invoice = await create_payment_link(db, project_id, amount=10000, project_name=project.name)

                # Generate invoice PDF
                pdf_path = os.path.join(output_dir, "invoice.pdf")
                await generate_invoice_pdf(invoice, project.name, pdf_path)

                invoice.pdf_path = pdf_path
                await db.commit()

                # Package everything
                code_dir = os.path.join(output_dir, "code")
                landing_dir = os.path.join(output_dir, "landing")
                promo_dir = os.path.join(output_dir, "promo")

                readme = f"""# {project.name}

Generated by AI Product Studio v3.0

## Project Idea
{project.client_idea}

## Contents
- `code/` - Generated application source code
- `landing/` - Landing page HTML
- `promo/` - Marketing materials (blog post, social posts)
- `invoice.pdf` - Payment invoice

## Quick Start
1. Extract the ZIP
2. Navigate to `code/` directory
3. Follow DEPLOY.md for deployment instructions

---
Built with AI Product Studio | Private Cloud | 100% Local LLM
"""

                deploy = """# Deployment Guide

## Prerequisites
- Docker 24.0+
- Docker Compose 2.0+
- 16GB RAM recommended

## Steps
1. Copy the `code/` directory to your server
2. Run `docker compose up -d` inside the code directory
3. Access the application at `http://localhost:3000`

## Environment Variables
Copy `.env.example` to `.env` and configure:
- DATABASE_URL
- REDIS_URL
- API keys

## Support
For issues, contact your AI Product Studio provider.
"""

                zip_path = package_deliverable(
                    project_id=project_id,
                    project_name=project.name,
                    code_dir=code_dir,
                    landing_dir=landing_dir,
                    promo_dir=promo_dir,
                    invoice_pdf=pdf_path,
                    readme_content=readme,
                    deploy_content=deploy,
                )

                job.status = JobStatus.COMPLETED
                job.result = {
                    "invoice_id": invoice.id,
                    "zip_path": zip_path,
                    "payment_link": invoice.stripe_payment_link,
                }
                project.status = ProjectStatus.COMPLETED
                await db.commit()

                return {"status": "completed", "invoice_id": invoice.id}

            except Exception as e:
                job.status = JobStatus.FAILED
                job.error = str(e)
                project.status = ProjectStatus.FAILED
                await db.commit()
                self.retry(countdown=60, exc=e)
                return {"error": str(e)}

    return asyncio.run(_run())
